add restart for pyscf, PBC has not yet been implemented.
lkwagner/autogenv2 pull request #17
Opened 2017-05-01 05:05 UTC by lichen5

2017-05-01 13:35 UTC, lkwagner requested changes
Hi, while this may work for your purposes, I don't think we can bring this into the codebase as it is.

2017-05-01 13:35 UTC, lkwagner commented on Manager.py
> +    if ('HF_done' in  lines) and ('All_done' not in lines):
This is specific to pyscf for a general function.

Looking for signals should be in the Reader object.

2017-05-01 13:35 UTC, lkwagner commented on PySCF.py
> +    lines = open(fname, 'r').read().split()
Here we're editing a file. This is a rather fragile thing to do. I would prefer to rewrite the file.

2017-05-01 13:35 UTC, lkwagner commented on pyscf2qwalk.py
> +  occup =[[[ int(i) for i in j] for j in k] for k in occup]
Can this have a bug when there is partial occupancy? Say we use smearing.

2017-05-01 13:35 UTC, lkwagner commented on PySCF.py
> +          outlines += ["m.__dict__.update(lib.chkfile.load('%s', 'scf'))\n"%chkfile]
Why are we updating the dict directly? The mf objects have methods that read in the check file.

2017-05-14 03:08 UTC, lichen5 commented on PySCF.py
> +    lines = open(fname, 'r').read().split()
Should I write it in another file with different name?

2017-05-14 03:08 UTC, lichen5 commented on PySCF.py
> +          outlines += ["m.__dict__.update(lib.chkfile.load('%s', 'scf'))\n"%chkfile]
Is that pyscf.lib.chkfile.load(chkfile, key)?

2017-05-15 14:42 UTC, armunoz commented on PySCF.py
> +          outlines += ["m.__dict__.update(lib.chkfile.load('%s', 'scf'))\n"%chkfile]
That should give you what you want, Li.

2017-05-15 15:48 UTC, lkwagner commented on PySCF.py
> +          outlines += ["m.__dict__.update(lib.chkfile.load('%s', 'scf'))\n"%chkfile]
I think it should be 
m. init_guess_by_chkfile()

Using the libs directly probably will not be general.

2017-05-15 15:51 UTC, lkwagner commented on PySCF.py
> +    lines = open(fname, 'r').read().split()
The PySCF writer doesn't need to know about which file to write to. The file management is not done at that level. It only needs to know that it is reading from a given check file.

This capability was already there in the pyscf writer. You need only to change the recipe to enable restarts, not the pyscf writer.

2017-06-02 13:31 UTC, closed without merging